package formatter

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/chenhg5/agencycli/internal/ctxbuild"
)

// codexFormatter generates the file layout for OpenAI Codex.
//
// Codex loads AGENTS.md files from the Git root down to the current working
// directory, concatenating them with later files taking precedence. It has no
// native @import syntax, so we produce a single merged AGENTS.md that contains
// all layers in order, with skills inlined at the end.
//
// Skill files (scripts etc.) are copied to .agencycli-skills/<name>/ and
// .codex/skills/<name>/ so Codex gets both a flattened prompt and a durable,
// Claude-style skill directory it can inspect.
//
// Output structure inside outDir:
//
//	AGENTS.md                  ← all layers merged, skills inlined
//	.agencycli/context/*.md    ← Claude-style context layer files for inspection
//	.agencycli-skills/<name>/  ← bundled skill files (scripts etc.)
//	.codex/skills/<name>/      ← SKILL.md + bundled files, mirroring .claude/skills
type codexFormatter struct{}

func (f *codexFormatter) Format(mc *ctxbuild.MergedContext, outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("codex: create output dir: %w", err)
	}

	// Deploy skill files first so we can resolve {{SKILL_DIR}} in prompts.
	resolved := resolveSkillsToDir(mc.Skills, outDir)
	wakeup := readCodexWakeup(outDir)
	if err := writeCodexContextLayers(mc.Layers, outDir); err != nil {
		return err
	}
	if err := writeCodexSkills(resolved, outDir); err != nil {
		return err
	}

	content := buildAgentsMD(mc.Layers, resolved, wakeup)
	path := filepath.Join(outDir, "AGENTS.md")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("codex: write AGENTS.md: %w", err)
	}
	return nil
}

// buildAgentsMD merges all context layers and skills into a single Markdown
// document suitable for Codex.
func buildAgentsMD(layers []ctxbuild.ContextLayer, skills []ctxbuild.SkillDef, wakeup string) string {
	var sb strings.Builder
	sb.WriteString("<!-- Generated by agencycli. Do not edit manually. Run `agencycli sync` to update. -->\n\n")
	sb.WriteString(codexRuntimeGuide())

	for i, layer := range layers {
		if i > 0 {
			sb.WriteString("\n---\n\n")
		}
		sb.WriteString(fmt.Sprintf("<!-- [agencycli] source: %s -->\n", layer.Source))
		sb.WriteString(strings.TrimSpace(layer.Content))
		sb.WriteString("\n")
	}

	if len(skills) > 0 {
		sb.WriteString("\n---\n\n")
		sb.WriteString("## Skills Reference\n\n")
		sb.WriteString("The following skills are available to you.\n\n")
		for _, sk := range skills {
			sb.WriteString(fmt.Sprintf("### %s\n\n", sk.Name))
			if sk.Description != "" {
				sb.WriteString(fmt.Sprintf("> %s\n\n", sk.Description))
			}
			if sk.Prompt != "" {
				sb.WriteString(strings.TrimSpace(sk.Prompt))
				sb.WriteString("\n\n")
			}
		}
	}

	if strings.TrimSpace(wakeup) != "" {
		sb.WriteString("\n---\n\n")
		sb.WriteString("## Wakeup Routine\n\n")
		sb.WriteString(strings.TrimSpace(wakeup))
		sb.WriteString("\n")
	}

	return sb.String()
}

func readCodexWakeup(outDir string) string {
	data, err := os.ReadFile(filepath.Join(outDir, ".agencycli", "context", "wakeup.md"))
	if err != nil {
		return ""
	}
	return string(data)
}

func codexRuntimeGuide() string {
	return `## AgencyCLI Runtime Guide

You are running as an agencycli agent. Keep shell commands executable and scoped:

- ` + "`AGENTS.md`" + ` is your primary instruction file. AgencyCLI also writes Claude-style context files under ` + "`.agencycli/context/`" + ` and skill files under ` + "`.codex/skills/`" + ` so you can inspect reusable procedures explicitly.
- Put only executable shell code in shell command strings. Do not append prose such as ` + "`in /path`" + ` or paste CLI help text such as ` + "`Use \"agencycli ... --help\"`" + ` back into a command.
- To run in a directory, use ` + "`cd /absolute/path && command`" + ` or the tool's working-directory option. Never write ` + "`command in /path`" + `.
- If a command prints usage/help output, treat it as diagnostic text. Read it, fix the flags, and retry once; do not execute the help sentence itself.
- Prefer ` + "`\"${AGENCYCLI_BIN:-agencycli}\" --dir \"${AGENCYCLI_ROOT}\" ...`" + ` over bare ` + "`agencycli`" + `.
- Current agent scope is available as ` + "`$AGENCYCLI_PROJECT`" + ` and ` + "`$AGENCYCLI_AGENT`" + `.
- Commands that inspect this agent's task queue must include both ` + "`--project`" + ` and ` + "`--agent`" + `.
- Correct task queue example:
  ` + "`\"${AGENCYCLI_BIN:-agencycli}\" --dir \"${AGENCYCLI_ROOT}\" task list --project \"${AGENCYCLI_PROJECT}\" --agent \"${AGENCYCLI_AGENT}\" --status pending --format json`" + `
- Correct completion example:
  ` + "`\"${AGENCYCLI_BIN:-agencycli}\" --dir \"${AGENCYCLI_ROOT}\" task done --id <task-id> --status success`" + `
- Correct async message example:
  ` + "`\"${AGENCYCLI_BIN:-agencycli}\" --dir \"${AGENCYCLI_ROOT}\" inbox send --to <project>/<agent> --body \"...\"`" + `
- For ` + "`inbox send`" + `, use ` + "`--body`" + `. ` + "`--message`" + ` is accepted only as a compatibility alias. ` + "`--from`" + ` defaults to the current agent when ` + "`$AGENCYCLI_PROJECT`" + ` and ` + "`$AGENCYCLI_AGENT`" + ` are set.
- Do not use ` + "`npx`" + `, ` + "`pnpm dlx`" + `, ` + "`npm install`" + `, ` + "`curl | sh`" + `, or other network installers unless the task explicitly asks for dependency installation. Prefer existing project scripts and local binaries such as ` + "`./node_modules/.bin/<tool>`" + `.
- Do not start long-lived dev servers such as ` + "`npm run dev`" + ` or ` + "`vite preview`" + ` in an unattended agent run. Prefer one-shot checks such as ` + "`npm run build`" + `, ` + "`npm test`" + `, static file inspection, or a short script that exits.
- For JavaScript or browser checks, do not put large inline scripts in one shell command. Write a small ` + "`.mjs`" + ` file and run ` + "`node path/to/script.mjs`" + ` so zsh quoting and globbing cannot corrupt the command.
- Quote shell patterns and JSON carefully. Avoid unquoted characters like ` + "`[`" + `, ` + "`]`" + `, ` + "`*`" + `, and ` + "`?`" + ` in zsh commands unless they are intentional globs.
- If an agencycli command returns a usage error, fix the command and retry once before concluding the task is blocked.

---

`
}

func writeCodexContextLayers(layers []ctxbuild.ContextLayer, outDir string) error {
	contextDir := filepath.Join(outDir, ".agencycli", "context")
	if err := os.MkdirAll(contextDir, 0o755); err != nil {
		return fmt.Errorf("codex: create context dir: %w", err)
	}
	for _, layer := range layers {
		filename := sourceToFilename(layer.Source) + ".md"
		path := filepath.Join(contextDir, filename)
		if err := os.WriteFile(path, []byte(layer.Content), 0o644); err != nil {
			return fmt.Errorf("codex: write layer %q: %w", layer.Source, err)
		}
	}
	return nil
}

func writeCodexSkills(skills []ctxbuild.SkillDef, outDir string) error {
	for _, sk := range skills {
		skillDir := filepath.Join(outDir, ".codex", "skills", sk.Name)
		if err := os.MkdirAll(skillDir, 0o755); err != nil {
			return fmt.Errorf("codex: create skill dir %q: %w", sk.Name, err)
		}
		absSkillDir, err := deploySkillFiles(sk, skillDir)
		if err != nil {
			return fmt.Errorf("codex: %w", err)
		}
		resolved := sk
		resolved.Prompt = resolveSkillDir(sk.Prompt, absSkillDir)
		if err := os.WriteFile(filepath.Join(skillDir, "SKILL.md"), []byte(buildSkillMD(resolved)), 0o644); err != nil {
			return fmt.Errorf("codex: write skill %q: %w", sk.Name, err)
		}
	}
	return nil
}
